import { Adjustment, Channel, Close, Exception, Kitchen, Money, Order, Reason, Settlement } from './domain.js'; import { Store } from './store.js';
const now=()=>new Date().toISOString();
function pushUnique<T extends {id:string}>(a:T[], v:T){if(!a.some(x=>x.id===v.id))a.push(v);}
export class ReconciliationService { constructor(public store=new Store()){}
 ingestOrders(rows:Omit<Order,'id'|'ingestedAt'>[]){for(const r of rows)pushUnique(this.store.data.orders,{...r,id:`order_${r.source}_${r.externalId}`,ingestedAt:now()});this.store.save();}
 ingestKitchen(rows:Omit<Kitchen,'id'|'ingestedAt'>[]){for(const r of rows)pushUnique(this.store.data.kitchens,{...r,id:`kitchen_${r.source}_${r.externalId}`,ingestedAt:now()});this.store.save();}
 ingestSettlements(rows:Omit<Settlement,'id'>[]){for(const r of rows)pushUnique(this.store.data.settlements,{...r,id:`settlement_${r.source}_${r.externalId}`});this.store.save();}
 exceptions(date:string){const orders=this.store.data.orders.filter(o=>o.businessDate===date); const out:Exception[]=[]; const add=(reason:Reason,o:Order,k?:Kitchen,s?:Settlement,detail='')=>{const x:Exception={id:`exception_${date}_${reason}_${o.id}_${s?.id??k?.id??''}`,date,reason,orderId:o.id,kitchenId:k?.id,settlementId:s?.id,sourceIds:[o.id,...(k?[k.id]:[]),...(s?[s.id]:[])],detail,createdAt:now()};pushUnique(this.store.data.exceptions,x);out.push(x);};
 for(const o of orders){const k=this.store.data.kitchens.find(x=>x.orderRef===o.externalId||x.orderRef===o.id); if(k&&o.money.paid===0)add('COOKED_UNPAID',o,k); if(!k&&o.money.paid>0&&o.status==='paid')add('PAID_UNCOOKED',o,undefined,undefined); if(k&&o.status==='cancelled')add('CANCELLED_AFTER_COOKING',o,k); const near=orders.filter(x=>x.id!==o.id&&x.customer===o.customer&&Math.abs(Date.parse(x.occurredAt)-Date.parse(o.occurredAt))<=5*60000);if(near.length)add('AMBIGUOUS_DUPLICATE',o,undefined,undefined,'Same customer within five minutes; retained as independent records'); const s=this.store.data.settlements.find(x=>x.orderRef===o.externalId);if(s){if(s.commission!==o.money.commission)add('COMMISSION_MISMATCH',o,undefined,s);if(s.platformDiscount!==o.money.platformDiscount)add('DISCOUNT_MISMATCH',o,undefined,s);}}
 this.store.save();return out; }
 reconcile(date:string){const exceptions=this.exceptions(date);const orders=this.store.data.orders.filter(x=>x.businessDate===date);const total=(f:(o:Order)=>number)=>orders.reduce((n,o)=>n+f(o),0);return {date,orders:orders.length,gross:total(o=>o.money.gross),platformDiscount:total(o=>o.money.platformDiscount),commission:total(o=>o.money.commission),paid:total(o=>o.money.paid),revenue:total(o=>o.money.paid-o.money.commission),exceptions};}
 close(date:string):Close { const old=this.store.data.closes.find(x=>x.date===date);if(old)return old;const r=this.reconcile(date);const c:Close={id:`close_${date}`,date,createdAt:now(),orderIds:this.store.data.orders.filter(x=>x.businessDate===date).map(x=>x.id),revenue:r.revenue,gross:r.gross,platformDiscount:r.platformDiscount,commission:r.commission,paid:r.paid,exceptionIds:r.exceptions.map(x=>x.id)};this.store.data.closes.push(c);this.store.save();return c;}
 adjust(){const made:Adjustment[]=[];for(const s of this.store.data.settlements){const close=this.store.data.closes.find(c=>c.date===s.businessDate);const o=this.store.data.orders.find(x=>x.externalId===s.orderRef);if(!close||!o)continue;const expected=o.money.paid-o.money.commission;const actual=s.settled-s.commission;const amount=actual-expected;if(amount===0)continue;const a:Adjustment={id:`adjustment_${close.id}_${s.id}`,closeId:close.id,settlementId:s.id,orderId:o.id,amount,reason:'SETTLEMENT_VARIANCE',createdAt:now()};const before=this.store.data.adjustments.length;pushUnique(this.store.data.adjustments,a);if(this.store.data.adjustments.length>before)made.push(a);const ex:Exception={id:`exception_${s.businessDate}_SETTLEMENT_VARIANCE_${o.id}_${s.id}`,date:s.businessDate,reason:'SETTLEMENT_VARIANCE',orderId:o.id,settlementId:s.id,sourceIds:[o.id,s.id,close.id],detail:`Settled ${actual} vs closed expected ${expected}`,createdAt:now()};pushUnique(this.store.data.exceptions,ex);if(s.commission!==o.money.commission){pushUnique(this.store.data.exceptions,{...ex,id:"exception_"+s.businessDate+"_COMMISSION_MISMATCH_"+o.id+"_"+s.id,reason:"COMMISSION_MISMATCH",detail:"Settlement commission mismatch"});}}
 this.store.save();return made;}
 list(){return this.store.data;}
}
export const order=(source:string,externalId:string,channel:Channel,date:string,customer:string,minute:string,money:Money,status:'paid'|'cancelled'='paid'):Omit<Order,'id'|'ingestedAt'>=>({source,externalId,channel,businessDate:date,occurredAt:`${date}T${minute}:00.000Z`,customer,status,money});
